from collections import Counter
import json
from pathlib import Path

import networkx as nx
import pandas as pd

# Category colors shared with other visualizations (choices/colors.json)
COLORS_PATH = Path(__file__).resolve().parent.parent / "choices" / "colors.json"

OUTPUT_JSONS = ["../sigmajs-fancy/public/dataset.json", "../d3/dataset.json"]

NODE_SCALING = 2
# GraphML file generated by Gephi
INPUT_GRAPHML = "../graphs/bipartite_podcasts_layout_threshold=1.graphml"

BOUND = 800
BOUNDING_BOX = {"x": [-BOUND, BOUND], "y": [-BOUND, BOUND]}

LABEL_THRESHOLD = 12

if __name__ == "__main__":
    G = nx.read_graphml(path=INPUT_GRAPHML)

    _nodes_df = pd.DataFrame.from_dict(
        dict(G.nodes(data=True)), orient="index"
    ).reset_index(drop=True)
    _edges_df = nx.to_pandas_edgelist(G=G)

    nodes_df = _nodes_df[["x", "y", "label", "size", "category", "views"]]
    edges_df = _edges_df[["source", "target"]]

    nodes_df["cluster"] = nodes_df["category"]
    nodes_df["cluster"].fillna("Other", inplace=True)
    nodes_df.drop("category", axis="columns", inplace=True)

    label_to_index = {
        t[0]: i
        for i, t in enumerate(
            Counter(list(edges_df["source"]) + list(edges_df["target"])).most_common()
        )
    }

    nodes_df["key"] = nodes_df["label"].map(label_to_index)
    nodes_df["size"] /= NODE_SCALING
    nodes = nodes_df.to_dict(orient="records")

    edges = [
        [label_to_index[e["source"]], label_to_index[e["target"]]]
        for e in edges_df.to_dict(orient="records")
    ]

    with open(COLORS_PATH, encoding="utf-8") as f:
        category_colors = json.load(f)
    default_color = "#888888"

    clusters = [k for k, _ in Counter(nodes_df["cluster"]).most_common()]

    data = {
        "nodes": nodes,
        "edges": edges,
        "clusters": [
            {"key": c, "clusterLabel": c, "color": category_colors.get(c, default_color)}
            for c in clusters
        ],
        "bbox": BOUNDING_BOX,
        "labelThreshold": LABEL_THRESHOLD,
    }

    for output_json in OUTPUT_JSONS:
        with open(output_json, "w") as f:
            json.dump(obj=data, fp=f, separators=(",", ":"))
